# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: my_datbase_test
  pool: 5
  timeout: 5000
  username: Vinicius
  password: 12345
  
production:
  adapter: postgresql
  database: my_datbase_production
  pool: 5
  timeout: 5000


cucumber:
  <<: *test